times = ('Flamengo', 'Palmeiras', 'Fluminense', 'Ceará', 'Red Bull Bragantino', 'Vasco da Gama', 'Juventude', 'Mirassol', 'Internacional', 'Botafogo', 'Fortaleza', 'Santos', 'Corinthians', 'São Paulo', 'Bahia', 'Cruzeiro', 'Atlético Mineiro', 'Vitória', 'Grêmio', 'Sport')
print('=' * 50)
print(f'Lista de times do Brasileirão: {times}')
print('=' * 50)
print(f'Os 5 primeiros times são {times[0:5]}')
print('=' * 50)
print(f'Os últimos 4 times são {times[-4:]}')
print('=' * 50)
print(f'Times em ordem alfabética: {sorted(times)}')
print('=' * 50)
print(f'O Flamengo está na {times.index("Flamengo")+1}ª posição')